#Пользователи
##Получить пользователя по email
GET http://localhost:6000/users/crane@light.com HTTP/1.1
Content-Type: application/json

###

##Создать / зарегистрировать нового пользователя
POST http://localhost:6000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "ClutchSek",
  "email": "green@gmail.com",
  "type": "обычный",
  "password": "gold12",
  "favoriteOffers": []
}

###

##Авторизовать пользователя
POST http://localhost:6000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "green@gmail.com",
  "password": "gold12"
}

###

##Обновить информацию о пользователе
PATCH http://localhost:6000/users/6542788fb2ebbcd60fa229ec HTTP/1.1
Content-Type: application/json

{
  "name": "AirJordanoBruno"
}

###

##Отправить изображение
PATCH http://localhost:6000/users/6536d3fe88a91f2474bba958/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="fileCheck.png"
Content-Type: image/png

< /home/alien/Изображения/Снимки экрана/fileCheck.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

##Проверить аутентификацию
GET http://localhost:6000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1Z0Bkb250ZmVhdC5jb20iLCJuYW1lIjoiUUF0ZXN0RnJlYWsiLCJpZCI6IjY1NDI3ODhmYjJlYmJjZDYwZmEyMjllYyIsImlhdCI6MTY5ODg1NTA1OSwiZXhwIjoxNjk5MDI3ODU5fQ.8QnZLPtrI_HVCeWloDH11isybxnUN2k5kzL89f2IFIU

###

##Добавить предложение в избранное
PUT http://localhost:6000/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImdyZWVuQGdtYWlsLmNvbSIsIm5hbWUiOiJDbHV0Y2hTZWsiLCJpZCI6IjY1NDJhYWUwYzYyMDQyM2M0ZTJhZWU5YyIsImlhdCI6MTY5ODg2Nzk2MSwiZXhwIjoxNjk5MDQwNzYxfQ.945rMTz1V_KIw3k5Fl46jUbath0LIRkbNmPharwVlGc
Content-Type: application/json

{
  "offerId": "654278662c6f94b5eeac4bb1",
  "isFavorite": true
}

###
