export const OFFER_CONSTANT_VALUES = {
  NAME: {
    MIN_LENGTH: 10,
    MAX_LENGTH: 100,
  },
  DESCRIPTION: {
    MIN_LENGTH: 20,
    MAX_LENGTH: 1024,
  },
  PREVIEW_IMAGE: {
    MAX_LENGTH: 256,
  },
  PLACE_IMAGES: {
    IMAGES_COUNT: 6,
  },
  RATING: {
    MIN_VALUE: 1,
    MAX_VALUE: 5,
  },
  ROOMS_AMOUNT: {
    MIN_VALUE: 1,
    MAX_VALUE: 8,
  },
  GUESTS_AMOUNT: {
    MIN_VALUE: 1,
    MAX_VALUE: 10,
  },
  PRICE: {
    MIN_VALUE: 100,
    MAX_VALUE: 100000,
  },
  DEFAULT_OFFER_COUNT: 60,
  PREMIUM_OFFERS_COUNT: 3,
} as const;
