# Комментарии
## Создание комментария
POST http://localhost:6000/comments/654278662c6f94b5eeac4bab HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImdyZWVuQGdtYWlsLmNvbSIsIm5hbWUiOiJDbHV0Y2hTZWsiLCJpZCI6IjY1NDJhYWUwYzYyMDQyM2M0ZTJhZWU5YyIsImlhdCI6MTY5ODg2Nzk2MSwiZXhwIjoxNjk5MDQwNzYxfQ.945rMTz1V_KIw3k5Fl46jUbath0LIRkbNmPharwVlGc
Content-Type: application/json


{
  "description": "This is test comment",
  "rating": 3,
  "offerId": "654278662c6f94b5eeac4bab"
}

###

