export const COMMENT_CONSTANT_VALUES = {
  DESCRIPTION: {
    MIN_LENGTH: 20,
    MAX_LENGTH: 1024,
  },
  RATING: {
    MIN_VALUE: 1,
    MAX_VALUE: 5,
  },
  DEFAULT_COMMENT_COUNT: 50,
} as const;

